name: pier
license: BSD3
maintainer: judah.jacobson@gmail.com
synopsis: Yet another Haskell build system.
description: >
    A build system for Haskell projects, built on top of
    [shake](http://shakebuild.com).
category: Development
github: judah/pier

dependencies:
  - base
  - Cabal
  - directory
  - shake

default-extensions:
  - BangPatterns
  - LambdaCase
  - FlexibleContexts
  - DeriveGeneric
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeFamilies
  - TypeSynonymInstances

library:
  source-dirs: 'src'
  dependencies:
    - aeson
    - base64-bytestring
    - binary
    - binary-orphans
    - bytestring
    - containers
    - cryptohash-sha256
    - hashable
    - lens
    - process
    - temporary
    - text
    - transformers
    - unix
    - unordered-containers
    - wreq
    - yaml

executables:
  pier:
    source-dirs: 'app'
    main: Main.hs
    ghc-options: -threaded -with-rtsopts=-I0
    dependencies:
      - optparse-applicative
      - split
      - pier
