name: pier
version: 0.1.0.0
license: BSD3
maintainer: judah.jacobson@gmail.com
synopsis: Yet another Haskell build system.
description: >
    A build system for Haskell projects, built on top of
    [shake](http://shakebuild.com).
category: Development
github: judah/pier

dependencies:
  - base >= 4.11.0
  - directory >= 1.3.1
  - Cabal >= 2.2.0.0
  - shake
  - unordered-containers

default-extensions:
  - BangPatterns
  - DeriveGeneric
  - FlexibleContexts
  - LambdaCase
  - MultiWayIf
  - NondecreasingIndentation
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeFamilies
  - TypeSynonymInstances

library:
  source-dirs: 'src'
  dependencies:
    - aeson
    - base64-bytestring
    - binary
    - binary-orphans
    - bytestring
    - containers
    - cryptohash-sha256
    - hashable
    - http-client
    - http-client-tls
    - http-types
    - process
    - temporary
    - text
    - transformers
    - unix
    - yaml

# Work around haskell/cabal#4739
when:
  - condition: os(darwin)
    ghc-options: -optP-Wno-nonportable-include-path

executables:
  pier:
    source-dirs: 'app'
    main: Main.hs
    ghc-options: -threaded -with-rtsopts=-I0
    dependencies:
      - optparse-applicative
      - split
      - pier
