name: stake
license: BSD3
maintainer: judah.jacobson@gmail.com
synopsis: Yet another Haskell build system.
description: >
    A build system for Haskell projects, built on top of
    [shake](http://shakebuild.com).
category: Development
github: judah/stake

dependencies:
  - aeson
  - base
  - base64-bytestring
  - binary
  - binary-orphans
  - bytestring
  - Cabal
  - containers
  - cryptohash-sha256
  - directory
  - hashable
  - lens
  - process
  - shake
  - transformers
  - unordered-containers
  - optparse-applicative
  - temporary
  - text
  - unix
  - wreq
  - yaml

default-extensions:
  - BangPatterns
  - LambdaCase
  - FlexibleContexts
  - DeriveGeneric
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeFamilies
  - TypeSynonymInstances

executables:
  stake:
    source-dirs: 'src'
    main: Development.Stake
    ghc-options: -threaded -with-rtsopts=-I0
