version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.1.10
    steps:
      - checkout
      - restore_cache:
          keys:
            - stack-cache-{{ arch }}-{{ .Branch }}-{{ epoch }}
            - stack-cache-{{ arch }}-{{ .Branch }}
            - stack-cache-{{ arch }}-master
      - run:
          command: |
            echo 'export PATH=$HOME/.local/bin:$PATH' >> $BASH_ENV
            mkdir -p $HOME/.local/bin
      - run:
          command: |
            sudo apt-get install libgmp3-dev uuid-runtime
            mkdir -p $HOME/.local/bin
            curl -L https://github.com/commercialhaskell/stack/releases/download/v1.6.1/stack-1.6.1-linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C $HOME/.local/bin '*/stack'

      # Build with `stack`
      - run: stack --no-terminal install happy weeder alex hlint
      - run: stack --no-terminal build --only-dependencies --fast --no-terminal
      - run: stack --no-terminal build --pedantic --fast --no-terminal

      - run: hlint .
      - run: weeder . --build

      # Run stake on some sample packages
      # Note: it currently uses the `stack.yaml` of this `stake` repo itself.
      - run: stack exec stake -- build happy alex lens hlint pandoc language-c stake -j 2

      - save_cache:
            key: stack-cache-{{ arch }}-{{ .Branch }}-{{ epoch }}
            paths:
                - ~/.stack
                - .stack-work
