version: 2
jobs:
  build:
    docker:
      - image: judah/pier-ci:v1
    steps:
      - checkout
      - restore_cache:
          keys:
            - stack-cache-v3-{{ arch }}-{{ .Branch }}
            - stack-cache-v3-{{ arch }}-master
      - run:
          command: |
            echo 'export PATH=$HOME/.local/bin:$PATH' >> $BASH_ENV

      # Build with `stack`
      - run: stack --no-terminal install weeder hlint
      - run: stack --no-terminal build --only-dependencies --fast --no-terminal
      - run: stack --no-terminal build --pedantic --fast --no-terminal

      - run: hlint .
      - run: weeder . --build

      # Run pier on some sample packages
      - run:
          command: |
            $(stack exec which pier) build -j4 \
                c2hs elm-core-sources hscolour hsndfile hsx2hs lens \
                network-multicast pandoc pier unix-time wreq xhtml yaml \
                X11-xft
      - run: $(stack exec which pier) build # also build pier's examples
      - run: $(stack exec which pier) run -j4 hlint --sandbox $PWD/src
      - run: $(stack exec which pier) run hlint src
      - run: 'echo "system-ghc: true" >> example/pier.yaml'
      - run: $(stack exec which pier) build text unix-compat

      - save_cache:
            key: stack-cache-v3-{{ arch }}-{{ .Branch }}-{{ epoch }}
            paths:
                - ~/.stack
                - .stack-work
