version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.1.10
    steps:
      - checkout
      - restore_cache:
          keys:
            - stack-cache-v2-{{ arch }}-{{ .Branch }}
            - stack-cache-v2-{{ arch }}-master
      - run:
          command: |
            echo 'export PATH=$HOME/.local/bin:$PATH' >> $BASH_ENV
            mkdir -p $HOME/.local/bin
      - run:
          command: |
            sudo apt-get install libgmp3-dev
            mkdir -p $HOME/.local/bin
            curl -L https://github.com/commercialhaskell/stack/releases/download/v1.6.1/stack-1.6.1-linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C $HOME/.local/bin '*/stack'

      # Build with `stack`
      - run: stack --no-terminal install weeder hlint
      - run: stack --no-terminal build --only-dependencies --fast --no-terminal
      - run: stack --no-terminal build --pedantic --fast --no-terminal

      - run: hlint .
      - run: weeder . --build

      # Run pier on some sample packages
      - run: $(stack exec which pier) build c2hs lens pandoc pier unix-time wreq xhtml yaml -j4
      - run: $(stack exec which pier) build # build examples too
      - run: $(stack exec which pier) run -j4 hlint --sandbox $PWD/src
      - run: $(stack exec which pier) run hlint src
      - run: 'echo "system-ghc: true" >> example/pier.yaml'
      - run: $(stack exec which pier) build text unix-compat

      - save_cache:
            key: stack-cache-v2-{{ arch }}-{{ .Branch }}-{{ epoch }}
            paths:
                - ~/.stack
                - .stack-work
